### ISSUE TITLE
Any specific reasons for where the data normalizer is placed

### ISSUE THREAD

**Issue by weitliu** [jfc43/robust-ood-detection#1]
Hello. 

I notice you normalize the data in the forward method instead of dataloader: https://github.com/jfc43/robust-ood-detection/blob/master/CIFAR/robust_ood_train.py#L153. Other than the gradient is not needed to be normalized in Odin and Mahalanobis, may I ask if there are other reasons to do so? For example, in some specific cases, the normalizer may behave differently when it is implemented in the dataloader than the model.forward?

**Comment by jfc43** [comment]
No. It is just an easier way to do adversarial attack. We don't need to normalize gradients during attack.

**Comment by weitliu** [comment]
Thank you so much. I will close the issue.
